### ISSUE TITLE
Will this also work for 30 mins long videos?

### ISSUE THREAD

**Issue by GlenGGG** [L-KID/Full-Video-Action-Recognition#2]
Hi, thank you for sharing your great work. 

I am also interested in using as many frames as possible to make predictions. I was wondering if your method would work for 30 mins long videos? My concern is that we still need to get the activation maps for more than 20,000 frames from a convolution layer. In practice, we find it hard to achieve due to limited GPU memory. 

Do you think your method is also suitable for our application? 

Thank you.

**Comment by L-KID** [comment]
Hi, thank you for your interest in this work! In our case, we tested only with ~4000 frames maximum. I think 30 mins long videos probably do not fit.
